- name: Install and Run Nginx Service
  hosts: web 
  become: yes 
  tasks:
  - name: Install nginx 
    ansible.builtin.package:
      name: nginx
      state: present 
  - name: Start nginx
    tags:
    - Start
    ansible.builtin.service:
      name: nginx
      state: started 
      enabled: yes 
  - name: stop nginx 
    ansible.builtin.service:
      name: nginx 
      state: stopped 
      enabled: yes 