- name: Print Course Information 
  hosts: web
  vars:
    COURSE: "Devops With AWS"
    DURATION: 120HRS
    TRAINER: "Siva Raj Kumar" 
  tasks:
  - name: Course Info 
    vars:
      COURSE: ansible
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, duration is {{ DURATION }} and trainer is {{ TRAINER }}"
      
  - name: Course Info
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, duration is {{ DURATION }} and trainer is {{ TRAINER }}"