- name: variables from files
  hosts: web 
  tasks:
  - name: vras from files 
    vars: 
      - course.yaml 
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, duration is {{ DURATION }} and trainer is {{ TRAINER }}"
      