- name: print number is greater than or equal to 15
  hosts: local
  connection: local
  vars:
    my_number: 15
  tasks:
  - name: number is greater than 10
    ansible.builtin.debug:
      msg: "Given number is {{ my_number }} greater than 10"
    when: my_number > 10

  - name: number is less than or eq to 10
    ansible.builtin.debug:
      msg: "Given number is {{ my_number }} less than or eq to 10"
    when: my_number <= 15