- name: installing multiple package
  hosts: local
  connection: local
  become: yes 
  tasks:
  - name: multiple packages 
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed 
  loop:
    - gcc
    - git
    - python 
