- name: packages
  hosts: local
  connection: local
  become: yes
  tasks: 
  - name: installing 
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    loop:
      - { name: 'gcc', state: 'absent' }
      - { name: "git", state: "present" }
      - { name: "nginx", state: "absent" }
      - { name: "zip", state: "present" }