- name: filters
  hosts: local
  connection: local
  tasks:
  - name: funtions
    ansible.builtin.debug:
      msg: "Hello {{ PERSON | default ('Ramu') }}"

  - name: converting string into list
    vars:
      fruits: "apple, Banana, Mango"
    ansible.builtin.debug:
      msg: "Fruits are {{ fruits | split(',')}}"

  - name: converting dict to list 
    vars:
      course:
        ci: Jenkins
        cloud: aws
        Iac: terraform
    ansible.builtin.debug:
      msg: "Course is : {{ course | dict2items }}"

  - name: converting list to dict
    vars: 
      course:
        - {'key': 'ci', 'value': 'Jenkins'}
        - {'key': 'cloud', 'value': 'aws'}
        - {'key': 'Iac', 'value': 'terraform'}
    ansible.builtin.debug:
      msg: "{{ course | items2dict }}"

      
    