; [web]
; 18.215.166.22 DURATION=10HRS TRAINER="Laxman" COURSE="ansible"  

[hi]
18.215.166.22

[local]
localhost ansible_user=ec2-user ansible_password=DevOps321



[local:vars]
DURATION="120HRS"
TRAINER="Ramu"
COURSE="Devops with AWS"